### ISSUE TITLE
Errors during build 

### ISSUE THREAD

**Issue by zakraicik** [joshlarsen/jekyll4-deploy-gh-pages#14]
Have you ever seen this type of error when running this action? 

![Screen Shot 2022-10-10 at 6 04 08 PM](https://user-images.githubusercontent.com/43297285/194974904-9c014d72-155b-4ba7-9607-5bc17e25863c.png)

It's based off this template repo 

https://github.com/CloudCannon/vonge-jekyll-bookshop-template/tree/main

Have the action set up in the following way 

```
name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './site/'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
```
